from sqlalchemy import Column, String, Float, DateTime, Integer
from sqlalchemy.sql.functions import now

from api.db.database import Base


class Prediction(Base):
    """Table used to store the inference requests from the users, and the results."""
    __tablename__ = 'predictions'
    task_id  = Column(String, primary_key=True, index=True)
    time_post = Column(DateTime(timezone=True), server_default=now())
    time_get = Column(DateTime(timezone=True), default=None)
    x = Column(Float, default=None)
    y = Column(Float, default=None)
    status = Column(String, default='')


# ---- Monitoring and metrics tables ----

class Event(Base):
    """Table used to store the events that can be generated by the application.
    This is very similar to a log file."""
    __tablename__ = 'events'
    id = Column(Integer, primary_key=True, index=True)
    event = Column(String, default='')
    time_event = Column(DateTime(timezone=True), server_default=now())
