version: '3.3'

networks:
  mlpnet:
  www:
    external: true

services:

  rabbitMQ:
    image: rabbitmq
    # ports:
    #   - 5672:5672
    networks:
      - mlpnet

  redis:
    image: redis
    # ports:
    #   - 6379:6379
    networks:
      - mlpnet

  worker:
    image: cas.mlp.worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    networks:
      - mlpnet

  api:
    image: cas.mlp.api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 4789:4789
    networks:
      - www
      - mlpnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlpapi.rule=Host(`mlpapi.artemis.idsia.ch`)"
      - "traefik.http.routers.mlpapi.entrypoints=web"
      - "traefik.http.services.mlpapi.loadbalancer.server.port=4789"

  grafana:
    image: grafana/grafana-oss
    ports: 
      - 3000:3000
    networks:
      - www
      - mlpnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlpgrafana.rule=Host(`grafana.artemis.idsia.ch`)"
      - "traefik.http.routers.mlpgrafana.entrypoints=web"
      - "traefik.http.services.mlpgrafana.loadbalancer.server.port=3000"

    