version: '3.3'

networks:
  mlpnet:
  www:
    external: true

services:

  rabbitmq:
    image: rabbitmq
    # ports: 5672
    networks:
      - mlpnet

  redis:
    image: redis
    # ports: 6379
    networks:
      - mlpnet

  worker:
    image: cas.mlp.worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_QUEUE=${CELERY_QUEUE}
    networks:
      - mlpnet

  api:
    image: cas.mlp.api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    ports:
      - 4789:4789
    networks:
      - www
      - mlpnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlpapi.rule=Host(`mlpapi.${DOMAIN}`)"
      - "traefik.http.routers.mlpapi.entrypoints=web"
      - "traefik.http.services.mlpapi.loadbalancer.server.port=4789"

  # grafana:
  #   image: grafana/grafana-oss
  #   ports: 
  #     - 3000:3000
  #   networks:
  #     - www
  #     - mlpnet
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.mlpgrafana.rule=Host(`grafana.${DOMAIN}`)"
  #     - "traefik.http.routers.mlpgrafana.entrypoints=web"
  #     - "traefik.http.services.mlpgrafana.loadbalancer.server.port=3000"
