{
 "title": "MLP Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Performamce", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active inferences",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "api_active_inferences", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Processing time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_processing_time_count[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Arguments: people",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m),\n  avg(people_num) AS \"people_num\",\n  avg(children) AS \"children\"\nFROM users\nWHERE\n  $__timeFilter(creation_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Argument: budget",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m),\n  avg(budget) AS \"budget\"\nFROM users\nWHERE\n  $__timeFilter(creation_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Arguments: age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m),\n  avg(age_avg) AS \"age_avg\",\n  avg(age_max) AS \"age_max\",\n  avg(age_min) AS \"age_min\",\n  avg(age_std) AS \"age_std\"\nFROM users\nWHERE\n  $__timeFilter(creation_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Argument: booleans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m),\n  avg(CAST(pool as int)) AS \"pool\",\n  avg(CAST(spa as int)) AS \"spa\",\n  avg(CAST(pet_friendly as int)) AS \"pets\",\n  avg(CAST(lake as int)) AS \"lake\",\n  avg(CAST(mountain as int)) AS \"mountain\",\n  avg(CAST(sport as int)) AS \"sport\"\nFROM users\nWHERE\n  $__timeFilter(creation_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}