from pathlib import Path
from sqlalchemy import (
    Column,
    TypeDecorator,
    ForeignKey,
    String,
    Float,
    DateTime,
    Integer,
    Boolean,
    Date,
)
from sqlalchemy.sql.functions import now
from sqlalchemy.orm import relationship

from .database import Base


# ---- Decorators ----


class PathType(TypeDecorator):
    """Decorator to enable the use of PathLike objects."""

    impl = String(1024)
    cache_ok = True

    def process_bind_param(self, value, dialect) -> str | None:
        """Converts the path to string."""
        if value is None:
            return None
        if isinstance(value, Path):
            return str(value)
        return str(value)

    def process_result_value(self, value, dialect) -> Path | None:
        """Converts a string to a Path object."""
        if value is None:
            return None
        return Path(value)


# ---- Dataset tables ----


class User(Base):
    """Table used to store all the data received with the user's requests."""

    __tablename__ = "users"
    user_id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    creation_time = Column(DateTime(timezone=True), server_default=now())
    people_num = Column(Integer, nullable=False)
    children_num = Column(Integer, nullable=False)
    age_avg = Column(Float, nullable=False)
    age_std = Column(Float, nullable=False)
    age_min = Column(Float, nullable=False)
    age_max = Column(Float, nullable=False)
    budget = Column(Integer, nullable=False)
    nights = Column(Integer, nullable=False)
    time_arrival = Column(Date, nullable=True)
    pool = Column(Boolean, default=False)
    spa = Column(Boolean, default=False)
    pet_friendly = Column(Boolean, default=False)
    lake = Column(Boolean, default=False)
    mountain = Column(Boolean, default=False)
    sport = Column(Boolean, default=False)


class Location(Base):
    """Table used to store all the locations."""

    __tablename__ = "locations"
    location_id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    creation_time = Column(DateTime(timezone=True), server_default=now())
    lat = Column(Float, nullable=True)
    lon = Column(Float, nullable=True)
    children = Column(Boolean, nullable=False)
    breakfast = Column(Boolean, nullable=False)
    lunch = Column(Boolean, nullable=False)
    dinner = Column(Boolean, nullable=False)
    price = Column(Float, nullable=False)
    has_pool = Column(Boolean, default=False)
    has_spa = Column(Boolean, default=False)
    animals = Column(Boolean, default=False)
    near_lake = Column(Boolean, default=False)
    near_mountains = Column(Boolean, default=False)
    has_sport = Column(Boolean, default=False)
    family_rating = Column(Float, nullable=False)
    outdoor_rating = Column(Float, nullable=False)
    food_rating = Column(Float, nullable=False)
    leisure_rating = Column(Float, nullable=False)
    service_rating = Column(Float, nullable=False)
    user_score = Column(Float, nullable=False)


# ---- Inference tables ----


class Inference(Base):
    """Table used to store the inference requests from the users, and the results."""

    __tablename__ = "inferences"
    task_id = Column(String, primary_key=True, index=True)
    time_creation = Column(DateTime(timezone=True), server_default=now())
    time_get = Column(DateTime(timezone=True), default=None)
    time_update = Column(DateTime(timezone=True), default=None)
    user_id = Column(Integer, ForeignKey("users.user_id"))
    status = Column(String, default="")

    user = relationship("User")


class Result(Base):
    """Table used to store the inference results from the ML model."""

    __tablename__ = "results"
    result_id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    task_id = Column(String, nullable=False)
    user_id = Column(Integer, ForeignKey("users.user_id"))
    location_id = Column(Integer, ForeignKey("locations.location_id"))
    score = Column(Float, nullable=False)
    label = Column(Integer, default=0)
    shown = Column(Boolean, default=False)

    user = relationship("User")
    location = relationship("Location")


# ---- Monitoring and metrics tables ----


class Event(Base):
    """Table used to store the events that can be generated by the application.

    This is very similar to a log file.
    """

    __tablename__ = "events"
    event_id = Column(Integer, primary_key=True, index=True)
    event = Column(String, default="")
    time_event = Column(DateTime(timezone=True), server_default=now())


# ---- Retraining tables ----


class Dataset(Base):
    """Table used to store information on dataset used during the training of a model.

    Use the filed `task_id` to find the used model.
    """

    __tablename__ = "datasets"
    task_id = Column(String, primary_key=True, index=True)
    result_id = Column(Integer, ForeignKey("results.result_id"), primary_key=True)
    time_creation = Column(DateTime(timezone=True), server_default=now())

    result = relationship("Result")


class Model(Base):
    """Table used to store information regarding models generated by the training task.

    Use the field `task_id` to find the used dataset.
    """

    __tablename__ = "models"
    task_id = Column(String, primary_key=True, index=True)
    time_creation = Column(DateTime(timezone=True), server_default=now())
    status = Column(String, default="")
    path = Column(PathType)
    use_percentage = Column(Float, default=0.0)
    train_acc = Column(Float, default=0.0)
    train_auc = Column(Float, default=0.0)
    train_pre = Column(Float, default=0.0)
    train_rec = Column(Float, default=0.0)
    train_f1 = Column(Float, default=0.0)
    test_acc = Column(Float, default=0.0)
    test_auc = Column(Float, default=0.0)
    test_pre = Column(Float, default=0.0)
    test_rec = Column(Float, default=0.0)
    test_f1 = Column(Float, default=0.0)
